### ISSUE TITLE
Language support

### ISSUE THREAD

**Issue by subhanjanOps** [sandwich-go/xconf#9]
**NOTE:** Can we have an English version of the readme or documentation for this tool?
Would appreciate it.

_Thanks and regards._

**Comment by timestee** [comment]
> 

I'll start with yes, all improvements are welcome and I'd love to see this library be accessible by more friends.

But it may take some time, before we finish it, if you have any questions, please feel free to contact me. I’m more than happy to help。

**Comment by subhanjanOps** [comment]
That was quick! now this looks nice.

Also, I'd like to contribute if you don’t mind.

**Comment by timestee** [comment]
> That was quick! now this looks nice.
> 
> Also, I'd like to contribute if you don’t mind.
Hi @subhanjanOps 

First, thank you for your message and for taking the time to play with the library.We would be very happy to welcome your contribution to the library (code, demo, samples, documentation).

Feel free to start on anything you want, let's just do it ;-)
